export const entityLinks = [
  { label: "Fall of the Western Roman Empire", type: "event", slug: "fall-of-western-rome" },
  { label: "Battle of Las Navas de Tolosa", type: "event", slug: "battle-of-las-navas-de-tolosa" },
  { label: "Madrigal de las Altas Torres", type: "location", slug: "madrigal-de-las-altas-torres" },
  { label: "Charlemagne Crowned Emperor", aliases: ["Imperial coronation of 800","Charlemagne crowned emperor"], type: "event", slug: "charlemagne-crowned" },
  { label: "Black Death Reaches Europe", aliases: ["Black Death"], type: "event", slug: "black-death-europe" },
  { label: "Norman Conquest of England", aliases: ["Norman Conquest"], type: "event", slug: "norman-conquest" },
  { label: "Battle of Stamford Bridge", type: "event", slug: "battle-of-stamford-bridge" },
  { label: "Bermersheim vor der Hoehe", type: "location", slug: "bermersheim-vor-der-hoehe" },
  { label: "First Crusade Proclaimed", aliases: ["First Crusade","First Crusade proclaimed"], type: "event", slug: "first-crusade-called" },
  { label: "Grand Duchy of Lithuania", aliases: ["Lithuania"], type: "location", slug: "grand-duchy-of-lithuania" },
  { label: "Fall of Constantinople", type: "event", slug: "fall-of-constantinople" },
  { label: "Battle of Bannockburn", type: "event", slug: "battle-of-bannockburn" },
  { label: "Isabella I of Castile", aliases: ["Isabella of Castile"], type: "person", slug: "isabella-of-castile" },
  { label: "Margaret I of Denmark", aliases: ["Margaret I"], type: "person", slug: "margaret-i" },
  { label: "Richard the Lionheart", aliases: ["Richard I"], type: "person", slug: "richard-the-lionheart" },
  { label: "Royal Frankish Annals", type: "artifact", slug: "royal-frankish-annals" },
  { label: "William the Conqueror", aliases: ["William I"], type: "person", slug: "william-the-conqueror" },
  { label: "Eleanor of Aquitaine", type: "person", slug: "eleanor-of-aquitaine" },
  { label: "Kingdom of Jerusalem", type: "location", slug: "kingdom-of-jerusalem" },
  { label: "Winchester Cathedral", type: "location", slug: "winchester-cathedral" },
  { label: "Battle of Agincourt", type: "event", slug: "battle-of-agincourt" },
  { label: "Battle of Manzikert", type: "event", slug: "battle-of-manzikert" },
  { label: "Hildegard of Bingen", type: "person", slug: "hildegard-of-bingen" },
  { label: "Kingdom of Scotland", aliases: ["Scotland"], type: "location", slug: "kingdom-of-scotland" },
  { label: "Las Navas de Tolosa", type: "location", slug: "las-navas-de-tolosa" },
  { label: "Lindisfarne Gospels", type: "artifact", slug: "lindisfarne-gospels" },
  { label: "Battle of Bouvines", type: "event", slug: "battle-of-bouvines" },
  { label: "Battle of Grunwald", type: "event", slug: "battle-of-grunwald" },
  { label: "Battle of Hastings", type: "event", slug: "battle-of-hastings" },
  { label: "Battle of Poitiers", type: "event", slug: "battle-of-poitiers" },
  { label: "Carolingian Empire", type: "location", slug: "carolingian-empire" },
  { label: "Hundred Years' War", aliases: ["Hundred Years’ War"], type: "event", slug: "hundred-years-war" },
  { label: "Kingdom of Castile", aliases: ["Castile"], type: "location", slug: "kingdom-of-castile" },
  { label: "Kingdom of Denmark", aliases: ["Denmark"], type: "location", slug: "kingdom-of-denmark" },
  { label: "Kingdom of England", aliases: ["England"], type: "location", slug: "kingdom-of-england" },
  { label: "Magna Carta Sealed", aliases: ["Magna Carta"], type: "event", slug: "magna-carta" },
  { label: "Almohad Caliphate", type: "location", slug: "almohad-caliphate" },
  { label: "Battle of Legnano", type: "event", slug: "battle-of-legnano" },
  { label: "Duchy of Normandy", aliases: ["Normandy"], type: "location", slug: "duchy-of-normandy" },
  { label: "Holy Roman Empire", aliases: ["Empire in the West"], type: "location", slug: "holy-roman-empire" },
  { label: "Kingdom of France", aliases: ["France"], type: "location", slug: "kingdom-of-france" },
  { label: "Kingdom of Norway", aliases: ["Norway"], type: "location", slug: "kingdom-of-norway" },
  { label: "Kingdom of Poland", aliases: ["Poland"], type: "location", slug: "kingdom-of-poland" },
  { label: "Kingdom of Wessex", type: "location", slug: "kingdom-of-wessex" },
  { label: "Sutton Hoo Helmet", type: "artifact", slug: "sutton-hoo-helmet" },
  { label: "Umayyad Caliphate", aliases: ["Umayyad forces"], type: "location", slug: "umayyad-caliphate" },
  { label: "Alfred the Great", type: "person", slug: "alfred-the-great" },
  { label: "Battle of Kosovo", type: "event", slug: "battle-of-kosovo" },
  { label: "Byzantine Empire", aliases: ["Eastern Roman Empire","Byzantium"], type: "location", slug: "byzantine-empire" },
  { label: "Fontevraud Abbey", type: "location", slug: "fontevraud-abbey" },
  { label: "Frankish Kingdom", aliases: ["Frankish Empire","Franks","Frankish forces"], type: "location", slug: "frankish-kingdom" },
  { label: "Medina del Campo", type: "location", slug: "medina-del-campo" },
  { label: "North Sea Empire", aliases: ["Cnut’s empire","Canute’s empire"], type: "location", slug: "north-sea-empire" },
  { label: "Sigurd of Norway", aliases: ["Sigurd Jorsalfar","Sigurd the Crusader"], type: "person", slug: "sigurd-of-norway" },
  { label: "Treaty of Verdun", aliases: ["Verdun partition"], type: "event", slug: "treaty-of-verdun" },
  { label: "Battle of Crécy", aliases: ["Battle of Crecy"], type: "event", slug: "battle-of-crecy" },
  { label: "Battle of Tours", aliases: ["Battle of Poitiers 732"], type: "event", slug: "battle-of-tours" },
  { label: "Bayeux Tapestry", type: "artifact", slug: "bayeux-tapestry" },
  { label: "Flensburg Fjord", type: "location", slug: "flensburg-fjord" },
  { label: "Ragnar Lothbrok", type: "person", slug: "ragnar-lothbrok" },
  { label: "Shroud of Turin", type: "artifact", slug: "shroud-of-turin" },
  { label: "Stamford Bridge", type: "location", slug: "stamford-bridge" },
  { label: "Sweyn Forkbeard", aliases: ["Svein Forkbeard"], type: "person", slug: "sweyn-forkbeard" },
  { label: "William Wallace", type: "person", slug: "william-wallace" },
  { label: "Cnut the Great", aliases: ["Canute","Knut the Great"], type: "person", slug: "cnut-the-great" },
  { label: "Constantinople", aliases: ["Byzantium"], type: "location", slug: "constantinople" },
  { label: "Lombard League", type: "location", slug: "lombard-league" },
  { label: "Ottoman Empire", aliases: ["Ottomans"], type: "location", slug: "ottoman-empire" },
  { label: "Teutonic Order", type: "location", slug: "teutonic-order" },
  { label: "Book of Kells", type: "artifact", slug: "book-of-kells" },
  { label: "Soborg Castle", type: "location", slug: "soborg-castle" },
  { label: "Third Crusade", type: "event", slug: "third-crusade" },
  { label: "Gainsborough", type: "location", slug: "gainsborough" },
  { label: "Kosovo Field", type: "location", slug: "kosovo-field" },
  { label: "Seljuk Turks", aliases: ["Seljuk forces"], type: "location", slug: "seljuk-turks" },
  { label: "Bannockburn", type: "location", slug: "bannockburn" },
  { label: "Charlemagne", aliases: ["Charles the Great","Carolus Magnus"], type: "person", slug: "charlemagne" },
  { label: "Codex Gigas", type: "artifact", slug: "codex-gigas" },
  { label: "Joan of Arc", type: "person", slug: "joan-of-arc" },
  { label: "Magna Carta", aliases: ["Magna Carta document"], type: "artifact", slug: "magna-carta-document" },
  { label: "Northumbria", type: "location", slug: "northumbria" },
  { label: "Rupertsberg", type: "location", slug: "rupertsberg" },
  { label: "Shaftesbury", type: "location", slug: "shaftesbury" },
  { label: "al-Andalus", type: "location", slug: "al-andalus" },
  { label: "Winchester", type: "location", slug: "winchester" },
  { label: "Agincourt", type: "location", slug: "agincourt" },
  { label: "Aquitaine", type: "location", slug: "aquitaine" },
  { label: "Elderslie", type: "location", slug: "elderslie" },
  { label: "Manzikert", type: "location", slug: "manzikert" },
  { label: "Mehmed II", aliases: ["Mehmed the Conqueror","Fatih Sultan Mehmed"], type: "person", slug: "mehmed-ii" },
  { label: "Bouvines", type: "location", slug: "bouvines" },
  { label: "Damascus", type: "location", slug: "damascus" },
  { label: "Grunwald", type: "location", slug: "grunwald" },
  { label: "Hastings", type: "location", slug: "hastings" },
  { label: "Poitiers", type: "location", slug: "poitiers" },
  { label: "Roskilde", aliases: ["Roskilde Cathedral"], type: "location", slug: "roskilde" },
  { label: "Domremy", type: "location", slug: "domremy" },
  { label: "Falaise", type: "location", slug: "falaise" },
  { label: "Joyeuse", type: "artifact", slug: "joyeuse" },
  { label: "Legnano", type: "location", slug: "legnano" },
  { label: "Saladin", type: "person", slug: "saladin" },
  { label: "Wantage", type: "location", slug: "wantage" },
  { label: "Aachen", aliases: ["Aachen Cathedral","Palace Chapel at Aachen"], type: "location", slug: "aachen" },
  { label: "Chalus", type: "location", slug: "chalus" },
  { label: "Edirne", type: "location", slug: "edirne" },
  { label: "London", type: "location", slug: "london" },
  { label: "Oxford", type: "location", slug: "oxford" },
  { label: "Papacy", aliases: ["Papal States","bishop of Rome","papal authority"], type: "location", slug: "papacy" },
  { label: "Tikrit", type: "location", slug: "tikrit" },
  { label: "Crecy", aliases: ["Crécy"], type: "location", slug: "crecy" },
  { label: "Rouen", type: "location", slug: "rouen" },
  { label: "Tours", type: "location", slug: "tours" },
  { label: "Oslo", type: "location", slug: "oslo" },
  { label: "Rome", type: "location", slug: "rome" }
]
