export const entityLinks = [
  { label: "Fall of the Western Roman Empire", type: "event", slug: "fall-of-western-rome" },
  { label: "Battle of Las Navas de Tolosa", type: "event", slug: "battle-of-las-navas-de-tolosa" },
  { label: "Madrigal de las Altas Torres", type: "location", slug: "madrigal-de-las-altas-torres" },
  { label: "Charlemagne Crowned Emperor", type: "event", slug: "charlemagne-crowned" },
  { label: "Black Death Reaches Europe", type: "event", slug: "black-death-europe" },
  { label: "Constantine XI Palaiologos", aliases: ["Constantine XI","Constantine Dragases"], type: "person", slug: "constantine-xi-palaiologos" },
  { label: "Norman Conquest of England", type: "event", slug: "norman-conquest" },
  { label: "Battle of Stamford Bridge", type: "event", slug: "battle-of-stamford-bridge" },
  { label: "Bermersheim vor der Hoehe", type: "location", slug: "bermersheim-vor-der-hoehe" },
  { label: "Christopher II of Denmark", aliases: ["Christoffer II"], type: "person", slug: "christopher-ii-of-denmark" },
  { label: "Abd al-Rahman al-Ghafiqi", aliases: ["Abdul Rahman Al Ghafiqi"], type: "person", slug: "abd-al-rahman-al-ghafiqi" },
  { label: "Christopher I of Denmark", aliases: ["Christoffer I"], type: "person", slug: "christopher-i-of-denmark" },
  { label: "Edward, the Black Prince", aliases: ["Edward of Woodstock","Black Prince"], type: "person", slug: "edward-the-black-prince" },
  { label: "First Crusade Proclaimed", type: "event", slug: "first-crusade-called" },
  { label: "Grand Duchy of Lithuania", type: "location", slug: "grand-duchy-of-lithuania" },
  { label: "Alfonso VIII of Castile", aliases: ["Alfonso the Noble"], type: "person", slug: "alfonso-viii-of-castile" },
  { label: "Charles VIII of Sweden", aliases: ["Karl Knutsson Bonde","Charles I of Norway"], type: "person", slug: "charles-viii-of-sweden" },
  { label: "Christian I of Denmark", aliases: ["Christian I","Christiern I"], type: "person", slug: "christian-i-of-denmark" },
  { label: "Christopher of Bavaria", aliases: ["Christopher III"], type: "person", slug: "christopher-of-bavaria" },
  { label: "Fall of Constantinople", type: "event", slug: "fall-of-constantinople" },
  { label: "Frederick I Barbarossa", aliases: ["Frederick Barbarossa","Frederick I"], type: "person", slug: "frederick-i-barbarossa" },
  { label: "Principality of Serbia", aliases: ["Moravian Serbia","Serbian-led Balkan coalition"], type: "location", slug: "principality-of-serbia" },
  { label: "Valdemar II of Denmark", aliases: ["Valdemar the Victorious","Valdemar Sejr"], type: "person", slug: "valdemar-ii-of-denmark" },
  { label: "Albert of Mecklenburg", aliases: ["Albrecht of Mecklenburg"], type: "person", slug: "albert-of-mecklenburg" },
  { label: "Battle of Bannockburn", type: "event", slug: "battle-of-bannockburn" },
  { label: "Edward III of England", aliases: ["Edward III"], type: "person", slug: "edward-iii-of-england" },
  { label: "Ferdinand of Flanders", aliases: ["Ferdinand, Count of Flanders","Ferrand of Flanders"], type: "person", slug: "ferdinand-of-flanders" },
  { label: "Isabella I of Castile", aliases: ["Isabella of Castile"], type: "person", slug: "isabella-of-castile" },
  { label: "Margaret I of Denmark", aliases: ["Margaret I","Margaret of Denmark","Margaret of the Kalmar Union"], type: "person", slug: "margaret-i" },
  { label: "Richard the Lionheart", aliases: ["Richard I"], type: "person", slug: "richard-the-lionheart" },
  { label: "Royal Frankish Annals", type: "artifact", slug: "royal-frankish-annals" },
  { label: "Valdemar I of Denmark", aliases: ["Valdemar the Great"], type: "person", slug: "valdemar-i-of-denmark" },
  { label: "William the Conqueror", aliases: ["William I"], type: "person", slug: "william-the-conqueror" },
  { label: "Wladyslaw II Jagiello", aliases: ["Władysław II Jagiełło","Jogaila"], type: "person", slug: "wladyslaw-ii-jagiello" },
  { label: "Edward II of England", aliases: ["Edward II"], type: "person", slug: "edward-ii-of-england" },
  { label: "Eleanor of Aquitaine", type: "person", slug: "eleanor-of-aquitaine" },
  { label: "Haakon IV Haakonsson", aliases: ["Haakon the Old"], type: "person", slug: "haakon-iv-haakonsson" },
  { label: "Kingdom of Jerusalem", type: "location", slug: "kingdom-of-jerusalem" },
  { label: "Magnus III of Sweden", aliases: ["Magnus Ladulås","Magnus Birgersson"], type: "person", slug: "magnus-iii-of-sweden" },
  { label: "Sverker II of Sweden", aliases: ["Sverker the Younger"], type: "person", slug: "sverker-ii-of-sweden" },
  { label: "Ulrich von Jungingen", aliases: ["Ulrich of Jungingen"], type: "person", slug: "ulrich-von-jungingen" },
  { label: "Valdemar IV Atterdag", aliases: ["Valdemar Atterdag","Valdemar the Restorer"], type: "person", slug: "valdemar-iv-atterdag" },
  { label: "Winchester Cathedral", type: "location", slug: "winchester-cathedral" },
  { label: "Battle of Agincourt", type: "event", slug: "battle-of-agincourt" },
  { label: "Battle of Manzikert", type: "event", slug: "battle-of-manzikert" },
  { label: "Eric the Victorious", aliases: ["Erik Segersäll"], type: "person", slug: "eric-the-victorious" },
  { label: "Haakon VI of Norway", aliases: ["Haakon Magnusson"], type: "person", slug: "haakon-vi-of-norway" },
  { label: "Hildegard of Bingen", type: "person", slug: "hildegard-of-bingen" },
  { label: "Horik II of Denmark", aliases: ["Hårik II","Erik Barn"], type: "person", slug: "horik-ii-of-denmark" },
  { label: "Kingdom of Scotland", aliases: ["Scotland"], type: "location", slug: "kingdom-of-scotland" },
  { label: "Las Navas de Tolosa", type: "location", slug: "las-navas-de-tolosa" },
  { label: "Lindisfarne Gospels", type: "artifact", slug: "lindisfarne-gospels" },
  { label: "Magnus VI Lawmender", aliases: ["Magnus the Lawmender","Magnus Haakonsson"], type: "person", slug: "magnus-vi-lawmender" },
  { label: "Øystein I of Norway", aliases: ["Eystein I","Eystein Magnusson"], type: "person", slug: "oystein-i-of-norway" },
  { label: "Philip II of France", aliases: ["Philip Augustus"], type: "person", slug: "philip-ii-of-france" },
  { label: "Philip VI of France", aliases: ["Philip of Valois"], type: "person", slug: "philip-vi-of-france" },
  { label: "Romanos IV Diogenes", aliases: ["Romanus IV Diogenes"], type: "person", slug: "romanos-iv-diogenes" },
  { label: "Sigurd the Crusader", aliases: ["Sigurd of Norway","Sigurd Jorsalfar"], type: "person", slug: "sigurd-of-norway" },
  { label: "Sverker I of Sweden", aliases: ["Sverker the Elder"], type: "person", slug: "sverker-i-of-sweden" },
  { label: "Sweyn II Estridsson", aliases: ["Sweyn Estridsson","Svend Estridsen"], type: "person", slug: "sweyn-ii-estridsson" },
  { label: "Battle of Bouvines", type: "event", slug: "battle-of-bouvines" },
  { label: "Battle of Grunwald", type: "event", slug: "battle-of-grunwald" },
  { label: "Battle of Hastings", type: "event", slug: "battle-of-hastings" },
  { label: "Battle of Poitiers", type: "event", slug: "battle-of-poitiers" },
  { label: "Carolingian Empire", type: "location", slug: "carolingian-empire" },
  { label: "Cnut VI of Denmark", aliases: ["Canute VI","Knud VI"], type: "person", slug: "cnut-vi-of-denmark" },
  { label: "County of Flanders", aliases: ["Flanders"], type: "location", slug: "county-of-flanders" },
  { label: "Eric IV of Denmark", aliases: ["Eric Ploughpenny","Erik Plovpenning"], type: "person", slug: "eric-iv-of-denmark" },
  { label: "Godfred of Denmark", aliases: ["Gudfred","Gøtrik","Godofredus"], type: "person", slug: "godfred-of-denmark" },
  { label: "Guido da Landriano", aliases: ["Guido da Landriano of Milan"], type: "person", slug: "guido-da-landriano" },
  { label: "Haakon V Magnusson", aliases: ["Haakon V of Norway"], type: "person", slug: "haakon-v-magnusson" },
  { label: "Hemming of Denmark", aliases: ["Hemming I"], type: "person", slug: "hemming-of-denmark" },
  { label: "Henry V of England", aliases: ["Henry V"], type: "person", slug: "henry-v-of-england" },
  { label: "Horik I of Denmark", aliases: ["Hårik","Erik I"], type: "person", slug: "horik-i-of-denmark" },
  { label: "Hundred Years' War", type: "event", slug: "hundred-years-war" },
  { label: "Kingdom of Castile", aliases: ["Castile"], type: "location", slug: "kingdom-of-castile" },
  { label: "Kingdom of Denmark", aliases: ["Denmark"], type: "location", slug: "kingdom-of-denmark" },
  { label: "Kingdom of England", aliases: ["England"], type: "location", slug: "kingdom-of-england" },
  { label: "Kingdom of Navarre", aliases: ["Navarre"], type: "location", slug: "kingdom-of-navarre" },
  { label: "Magna Carta Sealed", type: "event", slug: "magna-carta" },
  { label: "Olaf II Haraldsson", aliases: ["Saint Olaf","Olaf the Holy","Olaf Haraldsson"], type: "person", slug: "olaf-ii-haraldsson" },
  { label: "Valdemar of Sweden", aliases: ["Valdemar Birgersson"], type: "person", slug: "valdemar-of-sweden" },
  { label: "Almohad Caliphate", type: "location", slug: "almohad-caliphate" },
  { label: "Ayyubid Sultanate", aliases: ["Ayyubids"], type: "location", slug: "ayyubid-sultanate" },
  { label: "Battle of Legnano", type: "event", slug: "battle-of-legnano" },
  { label: "Duchy of Normandy", aliases: ["Normandy"], type: "location", slug: "duchy-of-normandy" },
  { label: "Eric II of Norway", aliases: ["Eirik Magnusson"], type: "person", slug: "eric-ii-of-norway" },
  { label: "Eric IX of Sweden", aliases: ["Saint Erik","Erik Jedvardsson"], type: "person", slug: "eric-ix-of-sweden" },
  { label: "Eric of Pomerania", aliases: ["Erik of Pomerania","Eric VII of Denmark","Eric XIII of Sweden","Eric III of Norway"], type: "person", slug: "eric-of-pomerania" },
  { label: "Eric V of Denmark", aliases: ["Eric Klipping","Erik Glipping"], type: "person", slug: "eric-v-of-denmark" },
  { label: "Holy Roman Empire", type: "location", slug: "holy-roman-empire" },
  { label: "John II of France", aliases: ["John the Good","Jean II le Bon"], type: "person", slug: "john-ii-of-france" },
  { label: "Kingdom of Aragon", aliases: ["Aragon"], type: "location", slug: "kingdom-of-aragon" },
  { label: "Kingdom of France", aliases: ["France"], type: "location", slug: "kingdom-of-france" },
  { label: "Kingdom of Norway", aliases: ["Norway"], type: "location", slug: "kingdom-of-norway" },
  { label: "Kingdom of Poland", type: "location", slug: "kingdom-of-poland" },
  { label: "Kingdom of Sweden", type: "location", slug: "kingdom-of-sweden" },
  { label: "Kingdom of Wessex", type: "location", slug: "kingdom-of-wessex" },
  { label: "Muhammad al-Nasir", aliases: ["Muhammad an-Nasir","Miramamolin"], type: "person", slug: "muhammad-al-nasir" },
  { label: "Olaf IV of Norway", aliases: ["Olaf II of Denmark","Oluf II"], type: "person", slug: "olaf-iv-of-norway" },
  { label: "Sutton Hoo Helmet", type: "artifact", slug: "sutton-hoo-helmet" },
  { label: "Sverre Sigurdsson", aliases: ["Sverre of Norway"], type: "person", slug: "sverre-sigurdsson" },
  { label: "Umayyad Caliphate", type: "location", slug: "umayyad-caliphate" },
  { label: "Alfred the Great", type: "person", slug: "alfred-the-great" },
  { label: "Battle of Kosovo", type: "event", slug: "battle-of-kosovo" },
  { label: "Birger Magnusson", aliases: ["Birger of Sweden"], type: "person", slug: "birger-magnusson" },
  { label: "Byzantine Empire", aliases: ["Eastern Roman Empire"], type: "location", slug: "byzantine-empire" },
  { label: "Charles d'Albret", aliases: ["Charles I d Albret","Charles I d'Albret"], type: "person", slug: "charles-d-albret" },
  { label: "Fontevraud Abbey", type: "location", slug: "fontevraud-abbey" },
  { label: "Frankish Kingdom", type: "location", slug: "frankish-kingdom" },
  { label: "Harald Bluetooth", aliases: ["Harald Blåtand","Harald Gormsson"], type: "person", slug: "harald-bluetooth" },
  { label: "Harold Godwinson", aliases: ["Harold II"], type: "person", slug: "harold-godwinson" },
  { label: "Medina del Campo", type: "location", slug: "medina-del-campo" },
  { label: "North Sea Empire", aliases: ["Cnut’s empire","Canute’s empire"], type: "location", slug: "north-sea-empire" },
  { label: "Robert the Bruce", aliases: ["Robert I of Scotland"], type: "person", slug: "robert-the-bruce" },
  { label: "Tostig Godwinson", aliases: ["Tostig Godwineson"], type: "person", slug: "tostig-godwinson" },
  { label: "Treaty of Verdun", type: "event", slug: "treaty-of-verdun" },
  { label: "Battle of Crécy", type: "event", slug: "battle-of-crecy" },
  { label: "Battle of Tours", type: "event", slug: "battle-of-tours" },
  { label: "Bayeux Tapestry", type: "artifact", slug: "bayeux-tapestry" },
  { label: "Crusader States", aliases: ["Outremer","Latin East"], type: "location", slug: "crusader-states" },
  { label: "Flensburg Fjord", type: "location", slug: "flensburg-fjord" },
  { label: "Haakon the Good", aliases: ["Haakon Haraldsson","Aðalsteinsfóstri"], type: "person", slug: "haakon-the-good" },
  { label: "Harald Fairhair", aliases: ["Haraldr Hárfagri"], type: "person", slug: "harald-fairhair" },
  { label: "Harald Hardrada", aliases: ["Harald Sigurdsson","Harald III of Norway"], type: "person", slug: "harald-hardrada" },
  { label: "Magnus Barefoot", aliases: ["Magnus III of Norway","Magnus Barelegs"], type: "person", slug: "magnus-barefoot" },
  { label: "Magnus Eriksson", aliases: ["Magnus IV of Sweden","Magnus VII of Norway"], type: "person", slug: "magnus-eriksson" },
  { label: "Magnus the Good", aliases: ["Magnus Olafsson"], type: "person", slug: "magnus-the-good" },
  { label: "Olaf Tryggvason", aliases: ["Olav Tryggvason"], type: "person", slug: "olaf-tryggvason" },
  { label: "Olof Skötkonung", aliases: ["Olaf the Swede"], type: "person", slug: "olof-skotkonung" },
  { label: "Ragnar Lothbrok", type: "person", slug: "ragnar-lothbrok" },
  { label: "Shroud of Turin", type: "artifact", slug: "shroud-of-turin" },
  { label: "Stamford Bridge", type: "location", slug: "stamford-bridge" },
  { label: "Sweyn Forkbeard", aliases: ["Svein Forkbeard","Svend Tveskæg"], type: "person", slug: "sweyn-forkbeard" },
  { label: "William Wallace", type: "person", slug: "william-wallace" },
  { label: "Charles Martel", aliases: ["Charles the Hammer"], type: "person", slug: "charles-martel" },
  { label: "Cnut the Great", aliases: ["Canute","Knut the Great"], type: "person", slug: "cnut-the-great" },
  { label: "Constantinople", aliases: ["Byzantium"], type: "location", slug: "constantinople" },
  { label: "Inge the Elder", aliases: ["Inge Stenkilsson"], type: "person", slug: "inge-the-elder" },
  { label: "Jelling Stones", type: "artifact", slug: "jelling-stones" },
  { label: "Lombard League", aliases: ["Lombard communes"], type: "location", slug: "lombard-league" },
  { label: "Ottoman Empire", aliases: ["Ottomans"], type: "location", slug: "ottoman-empire" },
  { label: "Teutonic Order", aliases: ["Teutonic Knights"], type: "location", slug: "teutonic-order" },
  { label: "Book of Kells", type: "artifact", slug: "book-of-kells" },
  { label: "Emund the Old", aliases: ["Emund den gamle"], type: "person", slug: "emund-the-old" },
  { label: "Eric Bloodaxe", aliases: ["Eirik Haraldsson"], type: "person", slug: "eric-bloodaxe" },
  { label: "Erik Knutsson", aliases: ["Eric X of Sweden","Erik the Survivor"], type: "person", slug: "erik-knutsson" },
  { label: "Knut Eriksson", aliases: ["Canute I of Sweden"], type: "person", slug: "knut-eriksson" },
  { label: "Soborg Castle", type: "location", slug: "soborg-castle" },
  { label: "Third Crusade", type: "event", slug: "third-crusade" },
  { label: "Gainsborough", type: "location", slug: "gainsborough" },
  { label: "Gorm the Old", aliases: ["Gorm the Languid"], type: "person", slug: "gorm-the-old" },
  { label: "Kalmar Union", type: "location", slug: "kalmar-union" },
  { label: "Kosovo Field", type: "location", slug: "kosovo-field" },
  { label: "Prince Lazar", aliases: ["Lazar Hrebeljanovic"], type: "person", slug: "prince-lazar" },
  { label: "Seljuk Turks", aliases: ["Great Seljuk Empire","Seljuk Empire","Seljuk forces"], type: "location", slug: "seljuk-turks" },
  { label: "Anund Jacob", aliases: ["Anund Jakob","James"], type: "person", slug: "anund-jacob" },
  { label: "Bannockburn", type: "location", slug: "bannockburn" },
  { label: "Birger Jarl", aliases: ["Birger Magnusson"], type: "person", slug: "birger-jarl" },
  { label: "Charlemagne", aliases: ["Charles the Great","Carolus Magnus"], type: "person", slug: "charlemagne" },
  { label: "Codex Gigas", type: "artifact", slug: "codex-gigas" },
  { label: "Joan of Arc", type: "person", slug: "joan-of-arc" },
  { label: "Magna Carta", type: "artifact", slug: "magna-carta-document" },
  { label: "Northumbria", type: "location", slug: "northumbria" },
  { label: "Rupertsberg", type: "location", slug: "rupertsberg" },
  { label: "Shaftesbury", type: "location", slug: "shaftesbury" },
  { label: "al-Andalus", type: "location", slug: "al-andalus" },
  { label: "Alp Arslan", aliases: ["Muhammad bin Dawud Chaghri","Alp Arslan of the Seljuks"], type: "person", slug: "alp-arslan" },
  { label: "Harthacnut", aliases: ["Hardecanute","Hörðaknútr"], type: "person", slug: "harthacnut" },
  { label: "Winchester", type: "location", slug: "winchester" },
  { label: "Agincourt", type: "location", slug: "agincourt" },
  { label: "Aquitaine", type: "location", slug: "aquitaine" },
  { label: "Elderslie", type: "location", slug: "elderslie" },
  { label: "Manzikert", type: "location", slug: "manzikert" },
  { label: "Mehmed II", aliases: ["Mehmed the Conqueror","Fatih Sultan Mehmed"], type: "person", slug: "mehmed-ii" },
  { label: "Bouvines", type: "location", slug: "bouvines" },
  { label: "Damascus", type: "location", slug: "damascus" },
  { label: "Grunwald", type: "location", slug: "grunwald" },
  { label: "Hastings", type: "location", slug: "hastings" },
  { label: "Poitiers", type: "location", slug: "poitiers" },
  { label: "Roskilde", type: "location", slug: "roskilde" },
  { label: "Vytautas", aliases: ["Vytautas the Great"], type: "person", slug: "vytautas" },
  { label: "Domremy", type: "location", slug: "domremy" },
  { label: "Falaise", type: "location", slug: "falaise" },
  { label: "Joyeuse", type: "artifact", slug: "joyeuse" },
  { label: "Legnano", type: "location", slug: "legnano" },
  { label: "Murad I", aliases: ["Murad Hudavendigar"], type: "person", slug: "murad-i" },
  { label: "Otto IV", aliases: ["Otto IV, Holy Roman Emperor"], type: "person", slug: "otto-iv" },
  { label: "Saladin", type: "person", slug: "saladin" },
  { label: "Stenkil", aliases: ["Steinkell"], type: "person", slug: "stenkil" },
  { label: "Wantage", type: "location", slug: "wantage" },
  { label: "Aachen", type: "location", slug: "aachen" },
  { label: "Chalus", type: "location", slug: "chalus" },
  { label: "Edirne", type: "location", slug: "edirne" },
  { label: "London", type: "location", slug: "london" },
  { label: "Oxford", type: "location", slug: "oxford" },
  { label: "Papacy", aliases: ["Papal States","bishop of Rome"], type: "location", slug: "papacy" },
  { label: "Tikrit", type: "location", slug: "tikrit" },
  { label: "Crecy", type: "location", slug: "crecy" },
  { label: "Rouen", type: "location", slug: "rouen" },
  { label: "Tours", type: "location", slug: "tours" },
  { label: "Oslo", type: "location", slug: "oslo" },
  { label: "Rome", type: "location", slug: "rome" }
]
