// entityLinks AUTO-GENERATED from server/data/history.json by
// scripts/gen-entity-links.mjs. Do not edit the entityLinks array by hand: run
// `node scripts/gen-entity-links.mjs` after adding or renaming articles. Curated
// aliases from the previous file are preserved and merged. This drives the
// body/timeline auto-linker in DetailPage.jsx. The hand-maintained
// ambiguousEntityAliases export below is preserved across regenerations.
export const entityLinks = [
  { label: "Abd al-Rahman al-Ghafiqi", aliases: ["Abdul Rahman Al Ghafiqi"], type: "person", slug: "abd-al-rahman-al-ghafiqi" },
  { label: "Abel of Denmark", aliases: ["Abel Valdemarsen","Abel of Schleswig"], type: "person", slug: "abel-of-denmark" },
  { label: "Adhemar of Le Puy", aliases: ["Adhemar de Monteil"], type: "person", slug: "adhemar-of-le-puy" },
  { label: "Æthelred I of Wessex", aliases: ["Aethelred I","Ethelred I"], type: "person", slug: "aethelred-i-of-wessex" },
  { label: "Afonso I of Portugal", aliases: ["Afonso Henriques","Afonso the Conqueror","Afonso o Conquistador"], type: "person", slug: "afonso-i-of-portugal" },
  { label: "Afonso II of Portugal", aliases: ["Afonso the Fat","Afonso o Gordo"], type: "person", slug: "afonso-ii-of-portugal" },
  { label: "Afonso III of Portugal", aliases: ["Afonso the Boulonnais","Afonso o Bolonhês"], type: "person", slug: "afonso-iii-of-portugal" },
  { label: "Afonso IV of Portugal", aliases: ["Afonso the Brave","Afonso o Bravo"], type: "person", slug: "afonso-iv-of-portugal" },
  { label: "Afonso V of Portugal", aliases: ["Afonso the African","Afonso o Africano"], type: "person", slug: "afonso-v-of-portugal" },
  { label: "Al-Adil I", aliases: ["Al-Adil","Saphadin"], type: "person", slug: "al-adil-i" },
  { label: "Al-Kamil", aliases: ["al-Malik al-Kamil"], type: "person", slug: "al-kamil" },
  { label: "Albert of Mecklenburg", aliases: ["Albrecht of Mecklenburg"], type: "person", slug: "albert-of-mecklenburg" },
  { label: "Alexios I Komnenos", aliases: ["Alexius I Comnenus","Alexios Komnenos"], type: "person", slug: "alexios-i-komnenos" },
  { label: "Alfonso VIII of Castile", aliases: ["Alfonso the Noble"], type: "person", slug: "alfonso-viii-of-castile" },
  { label: "Alfred the Great", type: "person", slug: "alfred-the-great" },
  { label: "Alp Arslan", aliases: ["Muhammad bin Dawud Chaghri","Alp Arslan of the Seljuks"], type: "person", slug: "alp-arslan" },
  { label: "Amalric I of Jerusalem", aliases: ["Amaury I"], type: "person", slug: "amalric-i-of-jerusalem" },
  { label: "Amalric II of Lusignan", aliases: ["Aimery of Cyprus","Aimery of Lusignan","Amalric II","Amaury de Lusignan"], type: "person", slug: "amalric-ii-of-lusignan" },
  { label: "Andrew II of Hungary", aliases: ["Andrew of Hungary"], type: "person", slug: "andrew-ii-of-hungary" },
  { label: "Anna Komnene", aliases: ["Anna Comnena"], type: "person", slug: "anna-komnene" },
  { label: "Anund Jacob", aliases: ["Anund Jakob","James"], type: "person", slug: "anund-jacob" },
  { label: "Baldwin I of Jerusalem", aliases: ["Baldwin of Boulogne"], type: "person", slug: "baldwin-i-of-jerusalem" },
  { label: "Baldwin I, Latin Emperor", aliases: ["Baldwin of Flanders","Baldwin IX of Flanders"], type: "person", slug: "baldwin-i-latin-emperor" },
  { label: "Baldwin II of Jerusalem", aliases: ["Baldwin of Bourcq"], type: "person", slug: "baldwin-ii-of-jerusalem" },
  { label: "Baldwin III of Jerusalem", aliases: ["Baudouin III"], type: "person", slug: "baldwin-iii-of-jerusalem" },
  { label: "Baldwin IV of Jerusalem", aliases: ["Baldwin the Leper"], type: "person", slug: "baldwin-iv-of-jerusalem" },
  { label: "Baldwin V of Jerusalem", aliases: ["Baldwin V","Baudouin V","Baldwin the Child"], type: "person", slug: "baldwin-v-of-jerusalem" },
  { label: "Balian of Ibelin", aliases: ["Balian d’Ibelin"], type: "person", slug: "balian-of-ibelin" },
  { label: "Baybars", aliases: ["al-Malik al-Zahir Baybars"], type: "person", slug: "baybars" },
  { label: "Bayezid I", aliases: ["Bayezid the Thunderbolt","Yıldırım Bayezid"], type: "person", slug: "bayezid-i" },
  { label: "Bayezid II", aliases: ["Bayezid the Just","Sofu Bayezid"], type: "person", slug: "bayezid-ii" },
  { label: "Bernard of Clairvaux", aliases: ["Saint Bernard"], type: "person", slug: "bernard-of-clairvaux" },
  { label: "Birger Jarl", aliases: ["Birger Magnusson"], type: "person", slug: "birger-jarl" },
  { label: "Birger Magnusson", aliases: ["Birger of Sweden"], type: "person", slug: "birger-magnusson" },
  { label: "Bohemond I of Antioch", aliases: ["Bohemond of Taranto"], type: "person", slug: "bohemond-i-of-antioch" },
  { label: "Boniface of Montferrat", aliases: ["Boniface I of Montferrat"], type: "person", slug: "boniface-of-montferrat" },
  { label: "Charlemagne", aliases: ["Charles the Great","Carolus Magnus"], type: "person", slug: "charlemagne" },
  { label: "Charles d'Albret", aliases: ["Charles I d Albret","Charles I d'Albret"], type: "person", slug: "charles-d-albret" },
  { label: "Charles IV of France", aliases: ["Charles the Fair","Charles le Bel"], type: "person", slug: "charles-iv-of-france" },
  { label: "Charles Martel", aliases: ["Charles the Hammer"], type: "person", slug: "charles-martel" },
  { label: "Charles of Anjou", aliases: ["Charles I of Anjou","Charles I of Sicily"], type: "person", slug: "charles-of-anjou" },
  { label: "Charles V of France", aliases: ["Charles the Wise","Charles le Sage"], type: "person", slug: "charles-v-of-france" },
  { label: "Charles VI of France", aliases: ["Charles the Mad","Charles the Beloved","Charles le Fol","Charles le Bien-Aimé"], type: "person", slug: "charles-vi-of-france" },
  { label: "Charles VII of France", aliases: ["Charles the Victorious","Charles the Well-Served","Charles le Victorieux"], type: "person", slug: "charles-vii-of-france" },
  { label: "Charles VIII of Sweden", aliases: ["Karl Knutsson Bonde","Charles I of Norway"], type: "person", slug: "charles-viii-of-sweden" },
  { label: "Christian I of Denmark", aliases: ["Christian I","Christiern I"], type: "person", slug: "christian-i-of-denmark" },
  { label: "Christopher I of Denmark", aliases: ["Christoffer I"], type: "person", slug: "christopher-i-of-denmark" },
  { label: "Christopher II of Denmark", aliases: ["Christoffer II"], type: "person", slug: "christopher-ii-of-denmark" },
  { label: "Christopher of Bavaria", aliases: ["Christopher III"], type: "person", slug: "christopher-of-bavaria" },
  { label: "Cnut the Great", aliases: ["Canute","Knut the Great"], type: "person", slug: "cnut-the-great" },
  { label: "Cnut VI of Denmark", aliases: ["Canute VI","Knud VI"], type: "person", slug: "cnut-vi-of-denmark" },
  { label: "Conrad III of Germany", aliases: ["Conrad III"], type: "person", slug: "conrad-iii-of-germany" },
  { label: "Conrad of Montferrat", aliases: ["Conrad I of Jerusalem"], type: "person", slug: "conrad-of-montferrat" },
  { label: "Constantine X Doukas", aliases: ["Konstantinos X Doukas"], type: "person", slug: "constantine-x-doukas" },
  { label: "Constantine XI Palaiologos", aliases: ["Constantine XI","Constantine Dragases"], type: "person", slug: "constantine-xi-palaiologos" },
  { label: "David II of Scotland", aliases: ["David Bruce"], type: "person", slug: "david-ii-of-scotland" },
  { label: "Denis of Portugal", aliases: ["Dinis I","Denis the Farmer King","Dinis o Lavrador","the Poet King"], type: "person", slug: "denis-of-portugal" },
  { label: "Edmund Ironside", aliases: ["Edmund II"], type: "person", slug: "edmund-ironside" },
  { label: "Edward I of England", aliases: ["Edward I","Edward Longshanks"], type: "person", slug: "edward-i-of-england" },
  { label: "Edward II of England", aliases: ["Edward II"], type: "person", slug: "edward-ii-of-england" },
  { label: "Edward III of England", aliases: ["Edward III"], type: "person", slug: "edward-iii-of-england" },
  { label: "Edward of Portugal", aliases: ["Duarte I","Edward the Philosopher King","Duarte o Eloquente"], type: "person", slug: "edward-of-portugal" },
  { label: "Edward the Confessor", aliases: ["Saint Edward the Confessor","Edward of England"], type: "person", slug: "edward-the-confessor" },
  { label: "Edward the Elder", aliases: ["Eadweard"], type: "person", slug: "edward-the-elder" },
  { label: "Edward, the Black Prince", aliases: ["Edward of Woodstock","Black Prince"], type: "person", slug: "edward-the-black-prince" },
  { label: "Eleanor of Aquitaine", type: "person", slug: "eleanor-of-aquitaine" },
  { label: "Emund the Old", aliases: ["Emund den gamle"], type: "person", slug: "emund-the-old" },
  { label: "Enrico Dandolo", aliases: ["Henry Dandolo"], type: "person", slug: "enrico-dandolo" },
  { label: "Eric Bloodaxe", aliases: ["Eirik Haraldsson"], type: "person", slug: "eric-bloodaxe" },
  { label: "Eric II of Norway", aliases: ["Eirik Magnusson"], type: "person", slug: "eric-ii-of-norway" },
  { label: "Eric IV of Denmark", aliases: ["Eric Ploughpenny","Erik Plovpenning"], type: "person", slug: "eric-iv-of-denmark" },
  { label: "Eric IX of Sweden", aliases: ["Saint Erik","Erik Jedvardsson"], type: "person", slug: "eric-ix-of-sweden" },
  { label: "Eric of Pomerania", aliases: ["Erik of Pomerania","Eric VII of Denmark","Eric XIII of Sweden","Eric III of Norway"], type: "person", slug: "eric-of-pomerania" },
  { label: "Eric the Victorious", aliases: ["Erik Segersäll"], type: "person", slug: "eric-the-victorious" },
  { label: "Eric V of Denmark", aliases: ["Eric Klipping","Erik Glipping"], type: "person", slug: "eric-v-of-denmark" },
  { label: "Eric VI of Denmark", aliases: ["Eric Menved","Erik Menved"], type: "person", slug: "eric-vi-of-denmark" },
  { label: "Erik Knutsson", aliases: ["Eric X of Sweden","Erik the Survivor"], type: "person", slug: "erik-knutsson" },
  { label: "Ferdinand I of Portugal", aliases: ["Fernando I","Ferdinand the Handsome","Ferdinand the Inconstant","Fernando o Formoso"], type: "person", slug: "ferdinand-i-of-portugal" },
  { label: "Ferdinand of Flanders", aliases: ["Ferdinand","Count of Flanders","Ferrand of Flanders","Ferdinand, Count of Flanders"], type: "person", slug: "ferdinand-of-flanders" },
  { label: "Frederick I Barbarossa", aliases: ["Frederick Barbarossa","Frederick I"], type: "person", slug: "frederick-i-barbarossa" },
  { label: "Frederick II, Holy Roman Emperor", aliases: ["Frederick II","Stupor Mundi"], type: "person", slug: "frederick-ii-holy-roman-emperor" },
  { label: "Fulcher of Chartres", aliases: ["Fulcherius Carnotensis"], type: "person", slug: "fulcher-of-chartres" },
  { label: "Gerard Thom", aliases: ["Blessed Gerard","Gerard of Jerusalem"], type: "person", slug: "gerard-thom" },
  { label: "Godfred of Denmark", aliases: ["Gudfred","Gøtrik","Godofredus"], type: "person", slug: "godfred-of-denmark" },
  { label: "Godfrey of Bouillon", aliases: ["Godfrey de Bouillon","Advocate of the Holy Sepulchre"], type: "person", slug: "godfrey-of-bouillon" },
  { label: "Gorm the Old", aliases: ["Gorm the Languid"], type: "person", slug: "gorm-the-old" },
  { label: "Guido da Landriano", aliases: ["Guido da Landriano of Milan"], type: "person", slug: "guido-da-landriano" },
  { label: "Guy of Lusignan", aliases: ["Guy de Lusignan"], type: "person", slug: "guy-of-lusignan" },
  { label: "Haakon IV Haakonsson", aliases: ["Haakon the Old"], type: "person", slug: "haakon-iv-haakonsson" },
  { label: "Haakon the Good", aliases: ["Haakon Haraldsson","Aðalsteinsfóstri"], type: "person", slug: "haakon-the-good" },
  { label: "Haakon V Magnusson", aliases: ["Haakon V of Norway"], type: "person", slug: "haakon-v-magnusson" },
  { label: "Haakon VI of Norway", aliases: ["Haakon Magnusson"], type: "person", slug: "haakon-vi-of-norway" },
  { label: "Håkon III Sverresson", aliases: ["Haakon III","Håkon Sverresson","Haakon Sverresson"], type: "person", slug: "hakon-iii-sverresson" },
  { label: "Harald Bluetooth", aliases: ["Harald Blåtand","Harald Gormsson"], type: "person", slug: "harald-bluetooth" },
  { label: "Harald Fairhair", aliases: ["Haraldr Hárfagri"], type: "person", slug: "harald-fairhair" },
  { label: "Harald Greycloak", aliases: ["Harald II Eiriksson","Harald Gråfell"], type: "person", slug: "harald-greycloak" },
  { label: "Harald Hardrada", aliases: ["Harald Sigurdsson","Harald III of Norway"], type: "person", slug: "harald-hardrada" },
  { label: "Harald II of Denmark", aliases: ["Harald Svendsen"], type: "person", slug: "harald-ii-of-denmark" },
  { label: "Harold Godwinson", aliases: ["Harold II"], type: "person", slug: "harold-godwinson" },
  { label: "Harold Harefoot", aliases: ["Harold I of England"], type: "person", slug: "harold-harefoot" },
  { label: "Harthacnut", aliases: ["Hardecanute","Hörðaknútr"], type: "person", slug: "harthacnut" },
  { label: "Hemming of Denmark", aliases: ["Hemming I"], type: "person", slug: "hemming-of-denmark" },
  { label: "Henry I of France", aliases: ["Henri Ier","Henry I Capet"], type: "person", slug: "henry-i-of-france" },
  { label: "Henry II of Castile", aliases: ["Henry of Trastámara","Enrique II","Henry the Fratricidal","el de las Mercedes"], type: "person", slug: "henry-ii-of-castile" },
  { label: "Henry II of Champagne", aliases: ["Henry of Champagne"], type: "person", slug: "henry-ii-of-champagne" },
  { label: "Henry II of England", aliases: ["Henry Plantagenet","Henry FitzEmpress"], type: "person", slug: "henry-ii-of-england" },
  { label: "Henry III of Castile", aliases: ["Henry the Sufferer","Enrique III","el Doliente","Henry the Infirm"], type: "person", slug: "henry-iii-of-castile" },
  { label: "Henry III of England", aliases: ["Henry of Winchester"], type: "person", slug: "henry-iii-of-england" },
  { label: "Henry IV of England", aliases: ["Henry Bolingbroke","Henry of Lancaster"], type: "person", slug: "henry-iv-of-england" },
  { label: "Henry of Flanders", aliases: ["Henry of Hainault","Henry I of Constantinople"], type: "person", slug: "henry-of-flanders" },
  { label: "Henry V of England", aliases: ["Henry V"], type: "person", slug: "henry-v-of-england" },
  { label: "Henry VI of England", aliases: ["Henry of Windsor"], type: "person", slug: "henry-vi-of-england" },
  { label: "Henry VI, Holy Roman Emperor", aliases: ["Heinrich VI"], type: "person", slug: "henry-vi-holy-roman-emperor" },
  { label: "Hermann von Salza", aliases: ["Hermann of Salza"], type: "person", slug: "hermann-von-salza" },
  { label: "Hildegard of Bingen", type: "person", slug: "hildegard-of-bingen" },
  { label: "Horik I of Denmark", aliases: ["Hårik","Erik I"], type: "person", slug: "horik-i-of-denmark" },
  { label: "Horik II of Denmark", aliases: ["Hårik II","Erik Barn"], type: "person", slug: "horik-ii-of-denmark" },
  { label: "Hugh Capet", aliases: ["Hugues Capet","Hugh the Great's son"], type: "person", slug: "hugh-capet" },
  { label: "Hugh de Payns", aliases: ["Hugues de Payens","Hugh of Payns"], type: "person", slug: "hugh-de-payns" },
  { label: "Igor of Kiev", aliases: ["Igor I of Kiev","Ihor of Kyiv","Ingvar (Norse equivalent name)"], type: "person", slug: "igor-of-kiev" },
  { label: "Imad ad-Din Zengi", aliases: ["Zengi"], type: "person", slug: "imad-ad-din-zengi" },
  { label: "Inge II Bårdsson", aliases: ["Inge Bårdsson","Inge II"], type: "person", slug: "inge-ii-bardsson" },
  { label: "Inge the Elder", aliases: ["Inge Stenkilsson"], type: "person", slug: "inge-the-elder" },
  { label: "Isabella I of Castile", aliases: ["Isabella of Castile"], type: "person", slug: "isabella-of-castile" },
  { label: "Isabella I of Jerusalem", aliases: ["Isabelle of Jerusalem"], type: "person", slug: "isabella-i-of-jerusalem" },
  { label: "Jacques de Molay", aliases: ["James of Molay"], type: "person", slug: "jacques-de-molay" },
  { label: "Jadwiga of Poland", aliases: ["Hedwig of Anjou","Saint Jadwiga"], type: "person", slug: "jadwiga-of-poland" },
  { label: "Jarl Håkon Sigurdsson", aliases: ["Haakon Sigurdsson","Håkon the Powerful","Hákon jarl","Earl Haakon of Lade"], type: "person", slug: "jarl-hakon-sigurdsson" },
  { label: "Jean de Joinville", aliases: ["John of Joinville"], type: "person", slug: "jean-de-joinville" },
  { label: "Joan of Arc", type: "person", slug: "joan-of-arc" },
  { label: "John Balliol", aliases: ["Toom Tabard","John de Balliol"], type: "person", slug: "john-balliol" },
  { label: "John Comyn", aliases: ["John Comyn of Badenoch","Red Comyn"], type: "person", slug: "john-comyn" },
  { label: "John I of Castile", aliases: ["Juan I of Castile","Juan I de Castilla"], type: "person", slug: "john-i-of-castile" },
  { label: "John I of Portugal", aliases: ["João I","John of Aviz","John of Good Memory","João de Boa Memória"], type: "person", slug: "john-i-of-portugal" },
  { label: "John II Komnenos", aliases: ["John the Good","Kaloïōannēs"], type: "person", slug: "john-ii-komnenos" },
  { label: "John II of Castile", aliases: ["Juan II","Juan II de Castilla"], type: "person", slug: "john-ii-of-castile" },
  { label: "John II of France", aliases: ["John the Good","Jean II le Bon"], type: "person", slug: "john-ii-of-france" },
  { label: "John II of Portugal", aliases: ["João II","the Perfect Prince","o Príncipe Perfeito"], type: "person", slug: "john-ii-of-portugal" },
  { label: "John of Brienne", aliases: ["Jean de Brienne"], type: "person", slug: "john-of-brienne" },
  { label: "John of England", aliases: ["John Lackland","Jean sans Terre"], type: "person", slug: "john-of-england" },
  { label: "John VIII Palaiologos", aliases: ["Ioannes VIII"], type: "person", slug: "john-viii-palaiologos" },
  { label: "Kerbogha", aliases: ["Kerbogha of Mosul"], type: "person", slug: "kerbogha" },
  { label: "Kilij Arslan I", aliases: ["Kilij Arslan","Kilij Arslan I of Rum"], type: "person", slug: "kilij-arslan-i" },
  { label: "Knut Eriksson", aliases: ["Canute I of Sweden"], type: "person", slug: "knut-eriksson" },
  { label: "Louis IX of France", aliases: ["Saint Louis"], type: "person", slug: "louis-ix-of-france" },
  { label: "Louis the Pious", aliases: ["Louis I","Ludovicus Pius"], type: "person", slug: "louis-the-pious" },
  { label: "Louis VI of France", aliases: ["Louis the Fat","Louis le Gros"], type: "person", slug: "louis-vi-of-france" },
  { label: "Louis VII of France", aliases: ["Louis VII"], type: "person", slug: "louis-vii-of-france" },
  { label: "Louis VIII of France", aliases: ["Louis the Lion"], type: "person", slug: "louis-viii-of-france" },
  { label: "Louis X of France", aliases: ["Louis the Quarrelsome","Louis le Hutin","Louis the Stubborn"], type: "person", slug: "louis-x-of-france" },
  { label: "Magnus Barefoot", aliases: ["Magnus III of Norway","Magnus Barelegs"], type: "person", slug: "magnus-barefoot" },
  { label: "Magnus Eriksson", aliases: ["Magnus IV of Sweden","Magnus VII of Norway"], type: "person", slug: "magnus-eriksson" },
  { label: "Magnus II of Norway", aliases: ["Magnus Haraldsson"], type: "person", slug: "magnus-ii-of-norway" },
  { label: "Magnus III of Sweden", aliases: ["Magnus Ladulås","Magnus Birgersson"], type: "person", slug: "magnus-iii-of-sweden" },
  { label: "Magnus the Good", aliases: ["Magnus Olafsson"], type: "person", slug: "magnus-the-good" },
  { label: "Magnus V Erlingsson", aliases: ["Magnus Erlingsson","Magnus V"], type: "person", slug: "magnus-v-erlingsson" },
  { label: "Magnus VI Lawmender", aliases: ["Magnus the Lawmender","Magnus Haakonsson"], type: "person", slug: "magnus-vi-lawmender" },
  { label: "Malik-Shah I", aliases: ["Jalāl al-Dawla Malik-Shāh"], type: "person", slug: "malik-shah-i" },
  { label: "Margaret I of Denmark", aliases: ["Margaret I","Margaret of Denmark","Margaret of the Kalmar Union"], type: "person", slug: "margaret-i" },
  { label: "Maria of Montferrat", aliases: ["Marie of Montferrat","Maria la Marquise","Marie de Montferrat"], type: "person", slug: "maria-of-montferrat" },
  { label: "Mehmed II", aliases: ["Mehmed the Conqueror","Fatih Sultan Mehmed"], type: "person", slug: "mehmed-ii" },
  { label: "Melisende of Jerusalem", aliases: ["Queen Melisende"], type: "person", slug: "melisende-of-jerusalem" },
  { label: "Michael VII Doukas", aliases: ["Michael Parapinakes"], type: "person", slug: "michael-vii-doukas" },
  { label: "Muhammad al-Nasir", aliases: ["Muhammad an-Nasir","Miramamolin"], type: "person", slug: "muhammad-al-nasir" },
  { label: "Murad I", aliases: ["Murad Hudavendigar"], type: "person", slug: "murad-i" },
  { label: "Murad II", aliases: ["Koca Murad"], type: "person", slug: "murad-ii" },
  { label: "Nikephoros III Botaneiates", aliases: ["Nicephorus III"], type: "person", slug: "nikephoros-iii-botaneiates" },
  { label: "Nuno Álvares Pereira", aliases: ["the Holy Constable","o Santo Condestável","Saint Nuno of Saint Mary","São Nuno de Santa Maria"], type: "person", slug: "nuno-alvares-pereira" },
  { label: "Nur ad-Din", aliases: ["Nur al-Din Mahmud","Nur ad-Din Zengi"], type: "person", slug: "nur-ad-din" },
  { label: "Olaf II Haraldsson", aliases: ["Saint Olaf","Olaf the Holy","Olaf Haraldsson"], type: "person", slug: "olaf-ii-haraldsson" },
  { label: "Olaf III of Norway", aliases: ["Olaf Kyrre","Olaf the Peaceful"], type: "person", slug: "olaf-iii-of-norway" },
  { label: "Olaf IV of Norway", aliases: ["Olaf II of Denmark","Oluf II"], type: "person", slug: "olaf-iv-of-norway" },
  { label: "Olaf Tryggvason", aliases: ["Olav Tryggvason"], type: "person", slug: "olaf-tryggvason" },
  { label: "Oleg of Novgorod", aliases: ["Oleg the Wise","Veshchiy Oleg","Oleh","Helgi (Norse equivalent name)"], type: "person", slug: "oleg-of-novgorod" },
  { label: "Olga of Kiev", aliases: ["Saint Olga","Olga the Wise","Helga (Norse equivalent name)","Equal-to-the-Apostles (Orthodox title)"], type: "person", slug: "olga-of-kiev" },
  { label: "Olof Skötkonung", aliases: ["Olaf the Swede"], type: "person", slug: "olof-skotkonung" },
  { label: "Orhan", aliases: ["Orhan Gazi","Orhan Bey"], type: "person", slug: "orhan" },
  { label: "Otto IV", aliases: ["Holy Roman Emperor","Otto IV, Holy Roman Emperor"], type: "person", slug: "otto-iv" },
  { label: "Øystein I of Norway", aliases: ["Eystein I","Eystein Magnusson"], type: "person", slug: "oystein-i-of-norway" },
  { label: "Pepin the Short", aliases: ["Pippin III","Pépin le Bref"], type: "person", slug: "pepin-the-short" },
  { label: "Peter I of Portugal", aliases: ["Pedro I","Peter the Just","Peter the Cruel","Pedro o Justiceiro"], type: "person", slug: "peter-i-of-portugal" },
  { label: "Peter of Castile", aliases: ["Peter the Cruel","Pedro I","Pedro el Cruel","Peter the Just","el Justiciero"], type: "person", slug: "peter-of-castile" },
  { label: "Peter the Hermit", aliases: ["Pierre l’Ermite"], type: "person", slug: "peter-the-hermit" },
  { label: "Philip I of France", aliases: ["Philippe Ier","Philip the Amorous"], type: "person", slug: "philip-i-of-france" },
  { label: "Philip II of France", aliases: ["Philip Augustus"], type: "person", slug: "philip-ii-of-france" },
  { label: "Philip III of France", aliases: ["Philip the Bold","Philippe le Hardi"], type: "person", slug: "philip-iii-of-france" },
  { label: "Philip IV of France", aliases: ["Philip the Fair","Philippe le Bel"], type: "person", slug: "philip-iv-of-france" },
  { label: "Philip V of France", aliases: ["Philip the Tall","Philippe le Long"], type: "person", slug: "philip-v-of-france" },
  { label: "Philip VI of France", aliases: ["Philip of Valois"], type: "person", slug: "philip-vi-of-france" },
  { label: "Pope Innocent III", aliases: ["Innocent III","Lotario dei Conti di Segni"], type: "person", slug: "pope-innocent-iii" },
  { label: "Pope Urban II", aliases: ["Urban II","Odo of Chatillon"], type: "person", slug: "pope-urban-ii" },
  { label: "Prince Lazar", aliases: ["Lazar Hrebeljanovic"], type: "person", slug: "prince-lazar" },
  { label: "Qutuz", aliases: ["Saif ad-Din Qutuz"], type: "person", slug: "qutuz" },
  { label: "Ragnar Lothbrok", type: "person", slug: "ragnar-lothbrok" },
  { label: "Raymond du Puy", aliases: ["Raymond of Le Puy"], type: "person", slug: "raymond-du-puy" },
  { label: "Raymond III of Tripoli", aliases: ["Raymond of Tripoli"], type: "person", slug: "raymond-iii-of-tripoli" },
  { label: "Raymond IV of Toulouse", aliases: ["Raymond of Saint-Gilles"], type: "person", slug: "raymond-iv-of-toulouse" },
  { label: "Reynald of Châtillon", aliases: ["Raynald of Châtillon"], type: "person", slug: "reynald-of-chatillon" },
  { label: "Richard II of England", aliases: ["Richard of Bordeaux"], type: "person", slug: "richard-ii-of-england" },
  { label: "Richard the Lionheart", aliases: ["Richard I"], type: "person", slug: "richard-the-lionheart" },
  { label: "Robert II of France", aliases: ["Robert the Pious","Robert le Pieux"], type: "person", slug: "robert-ii-of-france" },
  { label: "Robert the Bruce", aliases: ["Robert I of Scotland"], type: "person", slug: "robert-the-bruce" },
  { label: "Romanos IV Diogenes", aliases: ["Romanus IV Diogenes"], type: "person", slug: "romanos-iv-diogenes" },
  { label: "Rurik", aliases: ["Riurik","Rørik","Rorik (disputed identification)"], type: "person", slug: "rurik" },
  { label: "Saladin", type: "person", slug: "saladin" },
  { label: "Sancho I of Portugal", aliases: ["Sancho the Populator","Sancho o Povoador"], type: "person", slug: "sancho-i-of-portugal" },
  { label: "Sancho II of Portugal", aliases: ["Sancho the Pious","Sancho o Capelo","Sancho the Caped"], type: "person", slug: "sancho-ii-of-portugal" },
  { label: "Shirkuh", aliases: ["Asad ad-Din Shirkuh"], type: "person", slug: "shirkuh" },
  { label: "Sibylla of Jerusalem", aliases: ["Sibylla","Queen of Jerusalem","Sibylla, Queen of Jerusalem"], type: "person", slug: "sibylla-of-jerusalem" },
  { label: "Sigurd the Crusader", aliases: ["Sigurd of Norway","Sigurd Jorsalfar"], type: "person", slug: "sigurd-of-norway" },
  { label: "Stenkil", aliases: ["Steinkell"], type: "person", slug: "stenkil" },
  { label: "Sverker I of Sweden", aliases: ["Sverker the Elder"], type: "person", slug: "sverker-i-of-sweden" },
  { label: "Sverker II of Sweden", aliases: ["Sverker the Younger"], type: "person", slug: "sverker-ii-of-sweden" },
  { label: "Sverre Sigurdsson", aliases: ["Sverre of Norway"], type: "person", slug: "sverre-sigurdsson" },
  { label: "Sviatoslav I of Kiev", aliases: ["Svyatoslav Igorevich"], type: "person", slug: "sviatoslav-i-of-kiev" },
  { label: "Sweyn Forkbeard", aliases: ["Svein Forkbeard","Svend Tveskæg"], type: "person", slug: "sweyn-forkbeard" },
  { label: "Sweyn II Estridsson", aliases: ["Sweyn Estridsson","Svend Estridsen"], type: "person", slug: "sweyn-ii-estridsson" },
  { label: "Tancred, Prince of Galilee", aliases: ["Tancred of Hauteville","Tancred of Galilee"], type: "person", slug: "tancred-prince-of-galilee" },
  { label: "Tostig Godwinson", aliases: ["Tostig Godwineson"], type: "person", slug: "tostig-godwinson" },
  { label: "Tughril Beg", aliases: ["Toghrul I","Rukn al-Dunya wa-l-Din Tughril"], type: "person", slug: "tughril-beg" },
  { label: "Ulrich von Jungingen", aliases: ["Ulrich of Jungingen"], type: "person", slug: "ulrich-von-jungingen" },
  { label: "Valdemar I of Denmark", aliases: ["Valdemar the Great"], type: "person", slug: "valdemar-i-of-denmark" },
  { label: "Valdemar II of Denmark", aliases: ["Valdemar the Victorious","Valdemar Sejr"], type: "person", slug: "valdemar-ii-of-denmark" },
  { label: "Valdemar IV Atterdag", aliases: ["Valdemar Atterdag","Valdemar the Restorer"], type: "person", slug: "valdemar-iv-atterdag" },
  { label: "Valdemar of Sweden", aliases: ["Valdemar Birgersson"], type: "person", slug: "valdemar-of-sweden" },
  { label: "Vytautas", aliases: ["Vytautas the Great"], type: "person", slug: "vytautas" },
  { label: "William II of England", aliases: ["William Rufus"], type: "person", slug: "william-ii-of-england" },
  { label: "William the Conqueror", aliases: ["William I"], type: "person", slug: "william-the-conqueror" },
  { label: "William Wallace", type: "person", slug: "william-wallace" },
  { label: "Wladyslaw II Jagiello", aliases: ["Władysław II Jagiełło","Jogaila"], type: "person", slug: "wladyslaw-ii-jagiello" },
  { label: "Battle of Agincourt", type: "event", slug: "battle-of-agincourt" },
  { label: "Battle of Aljubarrota", aliases: ["Aljubarrota"], type: "event", slug: "battle-of-aljubarrota" },
  { label: "Battle of Arsuf", aliases: ["Arsuf"], type: "event", slug: "battle-of-arsuf" },
  { label: "Battle of Bannockburn", type: "event", slug: "battle-of-bannockburn" },
  { label: "Battle of Bouvines", type: "event", slug: "battle-of-bouvines" },
  { label: "Battle of Castillon", aliases: ["Castillon"], type: "event", slug: "battle-of-castillon" },
  { label: "Battle of Crécy", aliases: ["Crécy"], type: "event", slug: "battle-of-crecy" },
  { label: "Battle of Formigny", aliases: ["Formigny"], type: "event", slug: "battle-of-formigny" },
  { label: "Battle of Fulford", aliases: ["Fulford"], type: "event", slug: "battle-of-fulford" },
  { label: "Battle of Gestilren", type: "event", slug: "battle-of-gestilren" },
  { label: "Battle of Grunwald", type: "event", slug: "battle-of-grunwald" },
  { label: "Battle of Hastings", type: "event", slug: "battle-of-hastings" },
  { label: "Battle of Hattin", aliases: ["Hattin"], type: "event", slug: "battle-of-hattin" },
  { label: "Battle of Kosovo", aliases: ["Kosovo"], type: "event", slug: "battle-of-kosovo" },
  { label: "Battle of Las Navas de Tolosa", type: "event", slug: "battle-of-las-navas-de-tolosa" },
  { label: "Battle of Legnano", type: "event", slug: "battle-of-legnano" },
  { label: "Battle of Manzikert", type: "event", slug: "battle-of-manzikert" },
  { label: "Battle of Patay", aliases: ["Patay"], type: "event", slug: "battle-of-patay" },
  { label: "Battle of Poitiers", type: "event", slug: "battle-of-poitiers" },
  { label: "Battle of Stamford Bridge", type: "event", slug: "battle-of-stamford-bridge" },
  { label: "Battle of Stiklestad", type: "event", slug: "battle-of-stiklestad" },
  { label: "Battle of Svolder", type: "event", slug: "battle-of-svolder" },
  { label: "Battle of Tours", type: "event", slug: "battle-of-tours" },
  { label: "Battle of Verneuil", aliases: ["Verneuil"], type: "event", slug: "battle-of-verneuil" },
  { label: "Black Death Reaches Europe", type: "event", slug: "black-death-europe" },
  { label: "Charlemagne Crowned Emperor", type: "event", slug: "charlemagne-crowned" },
  { label: "Fall of Constantinople", type: "event", slug: "fall-of-constantinople" },
  { label: "Fall of the Western Roman Empire", type: "event", slug: "fall-of-western-rome" },
  { label: "First Crusade Proclaimed", type: "event", slug: "first-crusade-called" },
  { label: "Hundred Years' War", type: "event", slug: "hundred-years-war" },
  { label: "Magna Carta Sealed", type: "event", slug: "magna-carta" },
  { label: "Norman Conquest of England", type: "event", slug: "norman-conquest" },
  { label: "Siege of Orléans", aliases: ["Orléans"], type: "event", slug: "siege-of-orleans" },
  { label: "Siege of Rouen", type: "event", slug: "siege-of-rouen" },
  { label: "Third Crusade", type: "event", slug: "third-crusade" },
  { label: "Treaty of Edinburgh-Northampton", aliases: ["Treaty of Edinburgh Northampton"], type: "event", slug: "treaty-of-edinburgh-northampton" },
  { label: "Treaty of Verdun", type: "event", slug: "treaty-of-verdun" },
  { label: "Wars of Scottish Independence", aliases: ["First War of Scottish Independence"], type: "event", slug: "wars-of-scottish-independence" },
  { label: "Aachen", type: "location", slug: "aachen" },
  { label: "Agincourt", type: "location", slug: "agincourt" },
  { label: "al-Andalus", type: "location", slug: "al-andalus" },
  { label: "Almohad Caliphate", type: "location", slug: "almohad-caliphate" },
  { label: "Alvastra", type: "location", slug: "alvastra" },
  { label: "Aquitaine", type: "location", slug: "aquitaine" },
  { label: "Ayyubid Sultanate", aliases: ["Ayyubids"], type: "location", slug: "ayyubid-sultanate" },
  { label: "Bannockburn", type: "location", slug: "bannockburn" },
  { label: "Bergen", type: "location", slug: "bergen" },
  { label: "Berkeley Castle", type: "location", slug: "berkeley-castle" },
  { label: "Bermersheim vor der Hoehe", type: "location", slug: "bermersheim-vor-der-hoehe" },
  { label: "Bømlo", type: "location", slug: "bomlo" },
  { label: "Bouvines", type: "location", slug: "bouvines" },
  { label: "Bursa", type: "location", slug: "bursa" },
  { label: "Byzantine Empire", aliases: ["Eastern Roman Empire"], type: "location", slug: "byzantine-empire" },
  { label: "Cappadocia", type: "location", slug: "cappadocia" },
  { label: "Carolingian Empire", type: "location", slug: "carolingian-empire" },
  { label: "Chalus", type: "location", slug: "chalus" },
  { label: "Chateau de Vincennes", type: "location", slug: "chateau-de-vincennes" },
  { label: "Constantinople", aliases: ["Byzantium"], type: "location", slug: "constantinople" },
  { label: "Copenhagen", type: "location", slug: "copenhagen" },
  { label: "County of Flanders", aliases: ["Flanders"], type: "location", slug: "county-of-flanders" },
  { label: "Crecy", type: "location", slug: "crecy" },
  { label: "Crusader States", aliases: ["Outremer","Latin East"], type: "location", slug: "crusader-states" },
  { label: "Damascus", type: "location", slug: "damascus" },
  { label: "Domremy", type: "location", slug: "domremy" },
  { label: "Duchy of Normandy", aliases: ["Normandy"], type: "location", slug: "duchy-of-normandy" },
  { label: "Dunfermline Abbey", type: "location", slug: "dunfermline-abbey" },
  { label: "Edirne", type: "location", slug: "edirne" },
  { label: "Elderslie", type: "location", slug: "elderslie" },
  { label: "Falaise", type: "location", slug: "falaise" },
  { label: "Falsterbo", type: "location", slug: "falsterbo" },
  { label: "Finderup", type: "location", slug: "finderup" },
  { label: "Fitjar", type: "location", slug: "fitjar" },
  { label: "Flensburg Fjord", type: "location", slug: "flensburg-fjord" },
  { label: "Fontevraud Abbey", type: "location", slug: "fontevraud-abbey" },
  { label: "Frankish Kingdom", type: "location", slug: "frankish-kingdom" },
  { label: "Gainsborough", type: "location", slug: "gainsborough" },
  { label: "Gascony", type: "location", slug: "gascony" },
  { label: "Gebze", type: "location", slug: "gebze" },
  { label: "Gestilren", type: "location", slug: "gestilren" },
  { label: "Grand Duchy of Lithuania", type: "location", slug: "grand-duchy-of-lithuania" },
  { label: "Grunwald", type: "location", slug: "grunwald" },
  { label: "Gurre Castle", type: "location", slug: "gurre-castle" },
  { label: "Gutierre-Munoz", type: "location", slug: "gutierre-munoz" },
  { label: "Harzburg", type: "location", slug: "harzburg" },
  { label: "Hastings", type: "location", slug: "hastings" },
  { label: "Helsingborg", type: "location", slug: "helsingborg" },
  { label: "Holy Roman Empire", type: "location", slug: "holy-roman-empire" },
  { label: "Horodok", type: "location", slug: "horodok" },
  { label: "Hustad", type: "location", slug: "hustad" },
  { label: "Iskorosten", type: "location", slug: "iskorosten" },
  { label: "Jalbolung", type: "location", slug: "jalbolung" },
  { label: "Jelling", type: "location", slug: "jelling" },
  { label: "Kalmar Union", type: "location", slug: "kalmar-union" },
  { label: "Kievan Rus’", aliases: ["Kievan Rus","Kyivan Rus","Rus’"], type: "location", slug: "kievan-rus" },
  { label: "Kingdom of Aragon", aliases: ["Aragon"], type: "location", slug: "kingdom-of-aragon" },
  { label: "Kingdom of Castile", aliases: ["Castile"], type: "location", slug: "kingdom-of-castile" },
  { label: "Kingdom of Denmark", aliases: ["Denmark"], type: "location", slug: "kingdom-of-denmark" },
  { label: "Kingdom of England", aliases: ["England"], type: "location", slug: "kingdom-of-england" },
  { label: "Kingdom of France", aliases: ["France"], type: "location", slug: "kingdom-of-france" },
  { label: "Kingdom of Jerusalem", type: "location", slug: "kingdom-of-jerusalem" },
  { label: "Kingdom of Navarre", aliases: ["Navarre"], type: "location", slug: "kingdom-of-navarre" },
  { label: "Kingdom of Norway", aliases: ["Norway"], type: "location", slug: "kingdom-of-norway" },
  { label: "Kingdom of Poland", type: "location", slug: "kingdom-of-poland" },
  { label: "Kingdom of Portugal", type: "location", slug: "kingdom-of-portugal" },
  { label: "Kingdom of Scotland", aliases: ["Scotland"], type: "location", slug: "kingdom-of-scotland" },
  { label: "Kingdom of Sweden", type: "location", slug: "kingdom-of-sweden" },
  { label: "Kingdom of Wessex", type: "location", slug: "kingdom-of-wessex" },
  { label: "Kirkwall", type: "location", slug: "kirkwall" },
  { label: "Kosovo Field", type: "location", slug: "kosovo-field" },
  { label: "Lambeth", type: "location", slug: "lambeth" },
  { label: "Las Navas de Tolosa", type: "location", slug: "las-navas-de-tolosa" },
  { label: "Legnano", type: "location", slug: "legnano" },
  { label: "Lombard League", aliases: ["Lombard communes"], type: "location", slug: "lombard-league" },
  { label: "Lombardy", type: "location", slug: "lombardy" },
  { label: "London", type: "location", slug: "london" },
  { label: "Madrigal de las Altas Torres", type: "location", slug: "madrigal-de-las-altas-torres" },
  { label: "Manor of Cardross", aliases: ["Cardross"], type: "location", slug: "manor-of-cardross" },
  { label: "Mantes", type: "location", slug: "mantes" },
  { label: "Manzikert", type: "location", slug: "manzikert" },
  { label: "Marrakesh", type: "location", slug: "marrakesh" },
  { label: "Mecklenburg", type: "location", slug: "mecklenburg" },
  { label: "Medina del Campo", type: "location", slug: "medina-del-campo" },
  { label: "Melrose Abbey", type: "location", slug: "melrose-abbey" },
  { label: "Monmouth", type: "location", slug: "monmouth" },
  { label: "Nas Castle", type: "location", slug: "nas-castle" },
  { label: "Nogent-le-Roi", type: "location", slug: "nogent-le-roi" },
  { label: "North Sea Empire", aliases: ["Cnut’s empire","Canute’s empire"], type: "location", slug: "north-sea-empire" },
  { label: "Northumbria", type: "location", slug: "northumbria" },
  { label: "Novgorod", type: "location", slug: "novgorod" },
  { label: "Noyon", type: "location", slug: "noyon" },
  { label: "Nykobing Falster", type: "location", slug: "nykobing-falster" },
  { label: "Nykoping Castle", type: "location", slug: "nykoping-castle" },
  { label: "Oslo", type: "location", slug: "oslo" },
  { label: "Ottoman Empire", aliases: ["Ottomans"], type: "location", slug: "ottoman-empire" },
  { label: "Oxford", type: "location", slug: "oxford" },
  { label: "Oxus region", type: "location", slug: "oxus-region" },
  { label: "Papacy", aliases: ["Papal States","bishop of Rome"], type: "location", slug: "papacy" },
  { label: "Paris", type: "location", slug: "paris" },
  { label: "Poitiers", type: "location", slug: "poitiers" },
  { label: "Prilepac", type: "location", slug: "prilepac" },
  { label: "Principality of Serbia", aliases: ["Moravian Serbia","Serbian-led Balkan coalition"], type: "location", slug: "principality-of-serbia" },
  { label: "Proti", type: "location", slug: "proti" },
  { label: "Quierzy", type: "location", slug: "quierzy" },
  { label: "Ribe", type: "location", slug: "ribe" },
  { label: "Rogaland", type: "location", slug: "rogaland" },
  { label: "Rome", type: "location", slug: "rome" },
  { label: "Roskilde", type: "location", slug: "roskilde" },
  { label: "Rouen", type: "location", slug: "rouen" },
  { label: "Rugenwalde", type: "location", slug: "rugenwalde" },
  { label: "Rupertsberg", type: "location", slug: "rupertsberg" },
  { label: "Saleph River", type: "location", slug: "saleph-river" },
  { label: "Schlei", type: "location", slug: "schlei" },
  { label: "Scone", type: "location", slug: "scone" },
  { label: "Seljuk Turks", aliases: ["Great Seljuk Empire","Seljuk Empire","Seljuk forces"], type: "location", slug: "seljuk-turks" },
  { label: "Senieji Trakai", type: "location", slug: "senieji-trakai" },
  { label: "Shaftesbury", type: "location", slug: "shaftesbury" },
  { label: "Sheen Palace", type: "location", slug: "sheen-palace" },
  { label: "Soborg Castle", type: "location", slug: "soborg-castle" },
  { label: "Stainmore", type: "location", slug: "stainmore" },
  { label: "Stamford Bridge", type: "location", slug: "stamford-bridge" },
  { label: "Stiklestad", type: "location", slug: "stiklestad" },
  { label: "Stockholm", type: "location", slug: "stockholm" },
  { label: "Svolder", type: "location", slug: "svolder" },
  { label: "Swabia", type: "location", slug: "swabia" },
  { label: "Teutonic Order", aliases: ["Teutonic Knights"], type: "location", slug: "teutonic-order" },
  { label: "Tikrit", type: "location", slug: "tikrit" },
  { label: "Tonsberg", type: "location", slug: "tonsberg" },
  { label: "Tours", type: "location", slug: "tours" },
  { label: "Trakai", type: "location", slug: "trakai" },
  { label: "Ulster", type: "location", slug: "ulster" },
  { label: "Umayyad Caliphate", type: "location", slug: "umayyad-caliphate" },
  { label: "Uppsala", type: "location", slug: "uppsala" },
  { label: "Visingsö", type: "location", slug: "visingso" },
  { label: "Vordingborg", type: "location", slug: "vordingborg" },
  { label: "Wantage", type: "location", slug: "wantage" },
  { label: "Westminster", type: "location", slug: "westminster" },
  { label: "Winchester", type: "location", slug: "winchester" },
  { label: "Winchester Cathedral", type: "location", slug: "winchester-cathedral" },
  { label: "Bayeux Tapestry", type: "artifact", slug: "bayeux-tapestry" },
  { label: "Book of Kells", type: "artifact", slug: "book-of-kells" },
  { label: "Codex Gigas", type: "artifact", slug: "codex-gigas" },
  { label: "Declaration of Arbroath", type: "artifact", slug: "declaration-of-arbroath" },
  { label: "Jelling Stones", type: "artifact", slug: "jelling-stones" },
  { label: "Lindisfarne Gospels", type: "artifact", slug: "lindisfarne-gospels" },
  { label: "Magna Carta", type: "artifact", slug: "magna-carta-document" },
  { label: "Royal Frankish Annals", type: "artifact", slug: "royal-frankish-annals" },
  { label: "Shroud of Turin", type: "artifact", slug: "shroud-of-turin" },
  { label: "Arming Sword", aliases: ["Knightly sword","Single-handed sword"], type: "weaponArmor", slug: "arming-sword" },
  { label: "Bascinet", aliases: ["Basinet"], type: "weaponArmor", slug: "bascinet" },
  { label: "Battle Axe", aliases: ["War axe"], type: "weaponArmor", slug: "battle-axe" },
  { label: "Bill / Billhook", aliases: ["Billhook","English bill"], type: "weaponArmor", slug: "bill-billhook" },
  { label: "Brigandine", aliases: ["Brigandine armor"], type: "weaponArmor", slug: "brigandine" },
  { label: "Buckler", aliases: ["Small hand shield"], type: "weaponArmor", slug: "buckler" },
  { label: "Coat of Plates", aliases: ["Pair of plates"], type: "weaponArmor", slug: "coat-of-plates" },
  { label: "Crossbow", aliases: ["Arbalest"], type: "weaponArmor", slug: "crossbow" },
  { label: "Dagger / Rondel Dagger", aliases: ["Rondel dagger","Medieval dagger"], type: "weaponArmor", slug: "rondel-dagger" },
  { label: "Dane Axe", aliases: ["Danish axe","Two-handed axe"], type: "weaponArmor", slug: "dane-axe" },
  { label: "Falchion", aliases: ["Single-edged sword"], type: "weaponArmor", slug: "falchion" },
  { label: "Gambeson", aliases: ["Padded jack","Aketon"], type: "weaponArmor", slug: "gambeson" },
  { label: "Gothic Plate Armor", aliases: ["Gothic armor"], type: "weaponArmor", slug: "gothic-plate-armor" },
  { label: "Great Helm", aliases: ["Great helmet","Pot helm"], type: "weaponArmor", slug: "great-helm" },
  { label: "Halberd", aliases: ["Halbert"], type: "weaponArmor", slug: "halberd" },
  { label: "Hauberk", aliases: ["Mail shirt"], type: "weaponArmor", slug: "hauberk" },
  { label: "Heater Shield", aliases: ["Knightly shield"], type: "weaponArmor", slug: "heater-shield" },
  { label: "Hounskull Bascinet", aliases: ["Pig-faced bascinet","Houndskull bascinet"], type: "weaponArmor", slug: "hounskull-bascinet" },
  { label: "Javelin / Throwing Spear", aliases: ["Throwing spear","Javelin"], type: "weaponArmor", slug: "javelin-throwing-spear" },
  { label: "Joyeuse", aliases: ["Sword of Charlemagne","French coronation sword"], type: "weaponArmor", slug: "joyeuse" },
  { label: "Kettle Hat / Kettle Helm", aliases: ["Kettle helm","Chapel-de-fer"], type: "weaponArmor", slug: "kettle-hat" },
  { label: "Kite Shield", aliases: ["Kite-shaped shield"], type: "weaponArmor", slug: "kite-shield" },
  { label: "Lance", aliases: ["Knightly lance"], type: "weaponArmor", slug: "lance" },
  { label: "Longbow", aliases: ["English longbow"], type: "weaponArmor", slug: "longbow" },
  { label: "Longsword", aliases: ["Hand-and-a-half sword","Bastard sword"], type: "weaponArmor", slug: "longsword" },
  { label: "Mace", aliases: ["Flanged mace"], type: "weaponArmor", slug: "mace" },
  { label: "Mail Armor", aliases: ["Chainmail","Mail"], type: "weaponArmor", slug: "mail-armor" },
  { label: "Mail Coif", aliases: ["Chainmail coif"], type: "weaponArmor", slug: "mail-coif" },
  { label: "Nasal Helmet", aliases: ["Nasal helm"], type: "weaponArmor", slug: "nasal-helmet" },
  { label: "Pavise", aliases: ["Pavise shield"], type: "weaponArmor", slug: "pavise" },
  { label: "Plate Armor", aliases: ["Plate harness","Full plate armor"], type: "weaponArmor", slug: "plate-armor" },
  { label: "Poleaxe", aliases: ["Pollaxe"], type: "weaponArmor", slug: "poleaxe" },
  { label: "Sallet", aliases: ["Salade"], type: "weaponArmor", slug: "sallet" },
  { label: "Seax", aliases: ["Scramasax"], type: "weaponArmor", slug: "seax" },
  { label: "Shield", aliases: ["Medieval shield"], type: "weaponArmor", slug: "shield" },
  { label: "Spear", aliases: ["Thrusting spear"], type: "weaponArmor", slug: "spear" },
  { label: "Surcoat", aliases: ["Coat over armor"], type: "weaponArmor", slug: "surcoat" },
  { label: "Sutton Hoo Helmet", aliases: ["Sutton Hoo helm"], type: "weaponArmor", slug: "sutton-hoo-helmet" },
  { label: "Ulfberht Swords", aliases: ["+VLFBERHT+ swords","Vlfberht swords"], type: "weaponArmor", slug: "ulfberht-swords" },
  { label: "Viking Sword", aliases: ["Carolingian sword"], type: "weaponArmor", slug: "viking-sword" },
  { label: "War Bow", aliases: ["Medieval war bow"], type: "weaponArmor", slug: "war-bow" },
  { label: "War Hammer", aliases: ["Horseman’s hammer"], type: "weaponArmor", slug: "war-hammer" },
]

export const ambiguousEntityAliases = [
  {
    terms: ["Battle of Poitiers", "Tours-Poitiers"],
    possibleTargets: [
      {
        title: "Battle of Tours",
        label: "Battle of Tours",
        type: "event",
        slug: "battle-of-tours",
        date: "732",
        contextHints: [
          "732",
          "Charles Martel",
          "Umayyad",
          "al-Andalus",
          "Tours",
          "Franks",
          "Abd al-Rahman al-Ghafiqi",
          "Tours-Poitiers"
        ]
      },
      {
        title: "Battle of Poitiers",
        label: "Battle of Poitiers",
        type: "event",
        slug: "battle-of-poitiers",
        date: "1356",
        contextHints: [
          "1356",
          "Hundred Years",
          "Edward, the Black Prince",
          "Black Prince",
          "John II",
          "Anglo-Gascon",
          "English",
          "French"
        ]
      }
    ]
  }
]
